using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DotaHeroPicker
{
    public enum Hero
    {
        Abaddon = 1,
        Alchemist = 2,
        AncientApparition = 3,
        AntiMage = 4,
        ArcWarden = 5,
        Axe = 6,
        Bane = 7,
        Batrider = 8,

        Beastmaster = 9,
        Bloodseeker = 10,
        BountyHunter = 11,
        Brewmaster = 12,
        Bristleback = 13,
        Broodmother = 14,
        CentaurWarrunner = 15,
        ChaosKnight = 16,

        Chen = 17,
        Clinkz = 18,
        Clockwerk = 19,
        CrystalMaiden = 20,
        DarkSeer = 21,
        Dazzle = 22,
        DeathProphet = 23,
        Disruptor = 24,

        Doom = 25,
        DragonKnight = 26,
        DrowRanger = 27,
        EarthSpirit = 28,
        Earthshaker = 29,
        ElderTitan = 30,
        EmberSpirit = 31,
        Enchantress = 32,

        Enigma = 33,
        FacelessVoid = 34,
        Gyrocopter = 35,
        Huskar = 36,
        Invoker = 37,
        Io = 38,
        Jakiro = 39,
        Juggernaut = 40,

        KeeperOfTheLight = 41,
        Kunkka = 42,
        LegionCommander = 43,
        Leshrac = 44,
        Lich = 45,
        Lifestealer = 46,
        Lina = 47,
        Lion = 48,

        LoneDruid = 49,
        Luna = 50,
        Lycan = 51,
        Magnus = 52,
        Medusa = 53,
        Meepo = 54,
        Mirana = 55,
        Morphling = 56,

        NagaSiren = 57,
        NatureProphet = 58,
        Necrophos = 59,
        NightStalker = 60,
        NyxAssassin = 61,
        OgreMagi = 62,
        Omniknight = 63,
        Oracle = 64,

        OutworldDevourer = 65,
        PhantomAssassin = 66,
        PhantomLancer = 67,
        Phoenix = 68,
        Puck = 69,
        Pudge = 70,
        Pugna = 71,
        QueenOfPain = 72,

        Razor = 73,
        Riki = 74,
        Rubick = 75,
        SandKing = 76,
        ShadowDemon = 77,
        ShadowFiend = 78,
        ShadowShaman = 79,
        Silencer = 80,

        SkywrathMage = 81,
        Slardar = 82,
        Slark = 83,
        Sniper = 84,
        Spectre = 85,
        SpiritBreaker = 86,
        StormSpirit = 87,
        Sven = 88,

        Techies = 89,
        TemplarAssassin = 90,
        Terrorblade = 91,
        Tidehunter = 92,
        Timbersaw = 93,
        Tinker = 94,
        Tiny = 95,
        TreantProtector = 96,

        TrollWarlord = 97,
        Tusk = 98,
        Undying = 99,
        Ursa = 100,
        VengefulSpirit = 101,
        Venomancer = 102,
        Viper = 103,
        Visage = 104,

        Warlock = 105,
        Weaver = 106,
        Windranger = 107,
        WinterWyvern = 108,
        WitchDoctor = 109,
        WraithKing = 110,
        Zeus = 111
    }
}
